services:
  - type: web
    name: quilcount-api
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NPM_CONFIG_PRODUCTION
        value: "false"
      - key: NODE_ENV
        value: production
      - key: MONGO_URL
        sync: false
      - key: MONGO_DB_NAME
        value: QuilCount
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: CORS_ORIGIN
        value: https://quilcount.store
      - key: FRONTEND_URL
        value: https://quilcount.store
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
    disk:
      name: uploads
      mountPath: /opt/render/project/src/uploads
      sizeGB: 1
